### PR TITLE
Tournament : generating the URL + "copy link" button

### PR DESCRIPTION
**Pull request by Roshanakk**

### CODE REVIEW

**Review by svvoii — APPROVED** [review]
I have also added routing pattern from a_game app, which shall be there as well.

**Comment by Drewski6** [comment]
Has anyone else tried to build this?
When I run make up I get this in the terminal 

```web-app    | ModuleNotFoundError: No module named 'a_game.routing'
web-app    | 
web-app    | During handling of the above exception, another exception occurred:
web-app    | 
web-app    | Traceback (most recent call last):
web-app    |   File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
web-app    |     self.run()
web-app    |   File "/usr/local/lib/python3.12/threading.py", line 1012, in run
web-app    |     self._target(*self._args, **self._kwargs)
web-app    |   File "/usr/local/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
web-app    |     fn(*args, **kwargs)
web-app    |   File "/usr/local/lib/python3.12/site-packages/daphne/management/commands/runserver.py", line 128, in inner_run
web-app    |     application=self.get_application(options),
web-app    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-app    |   File "/usr/local/lib/python3.12/site-packages/daphne/management/commands/runserver.py", line 153, in get_application
web-app    |     return ASGIStaticFilesHandler(get_default_application())
web-app    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
web-app    |   File "/usr/local/lib/python3.12/site-packages/daphne/management/commands/runserver.py", line 31, in get_default_application
web-app    |     raise ImproperlyConfigured("Cannot import ASGI_APPLICATION module %r" % path)
web-app    | django.core.exceptions.ImproperlyConfigured: Cannot import ASGI_APPLICATION module '_main_project.asgi'```

Not sure if you guys get the same thing or if it's just me

**Comment by Drewski6** [comment]
I see the pull request also has merge conflicts. Can you fix these merge conflicts in another commit

**Review by Drewski6 — APPROVED** [review]
Builds now thanks to your changes! Looks good!

**Pull request merged**
